### ISSUE TITLE
第九讲课后作业（截止时间5月28日）

### ISSUE THREAD

**Issue by TieWay59** [X-lab2017/oss101#139]
> 实践任务部分见文章末尾

## 目标

写一个 github action，监听 issue comment 的创建事件，假如 comment 归属某些用户，那么就给这个 issue comment 添加一个互动 reaction，比如 eyes。

目的是帮助同学练习和深入理解 github action 的使用。

## 实现

https://github.com/X-lab2017/oss101/blob/b8024157f299d606ca8b2501382260085ffe481b/.github/workflows/add-reaction.yaml#L1-L22

```yaml
name: Add reaction
on:
  issue_comment:
    types: [created]
jobs:
  reaction:
    runs-on: ubuntu-latest
    if: |
      contains(fromJson('
        [
          "tc2000731",
          "will-ww",
        ]'), github.event.sender.login)
    steps:
      - name: Add reaction
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.TIEWAY59_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions \
            -d '{"content": "eyes"}'
```

示例仓库：[TieWay59/issue-action-test](https://github.com/TieWay59/issue-action-test)

原理是借助环境变量筛选条件然后 curl github api。

### Reaction API[^1]

```shell
curl -L \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/OWNER/REPO/issues/comments/COMMENT_ID/reactions \
  -d '{"content":"heart"}'
```

其中：

- `application/vnd.github+json` 是 Github API 使用的自定义媒体类型[^2]。它允许指定 API 版本和返回数据的格式。vnd 是 vendor 的缩写，表示这是一个供应商特定的媒体类型。
- `<YOUR-TOKEN>` 如果想要在 action 脚本中使用用户的 token，需要创建一个属于该用户的 Personal Access Token (PAT)，然后将它存储在仓库或组织的 secrets 中，然后在 action 中使用 `${{ secrets.PAT_NAME }}` 来引用它。上面的 `secrets.TIEWAY59_PAT` 就是我个人的 token。

### Personal Access Token[^3]

相关的设置藏在 `Settings > Developer settings > Personal access tokens` 小节中。创建 Fine-grained PAT 需要定制需要启用的读写权限，这一步需要稍微注意一些。

创建 PAT 以后， 打开仓库设置 `Settings > secrets > Actions` 点击 `new repository secret` 添加 PAT。这里设置的变量名就是之后脚本中 `secrets.` 可以访问的变量名。

## 实践任务

1. （基础版）阅读以上材料，个人向课程仓库提交 PR，把自己的用户 login 加入到监听列表。
   1. https://github.com/X-lab2017/oss101/blob/b8024157f299d606ca8b2501382260085ffe481b/.github/workflows/add-reaction.yaml#L10-L13
   2. 本作业的 PR 应该只包含一个 commit 名为 `` ci: add `<YOUR-LOGIN>` to reaction list ``，比如 `` ci: add `tieway59` to reaction list ``。 PR 标题与此 commit 标题一致。
   3. PR 正文部分可以留空。
   4. 作业 PR 应该只修改 `.github/workflows/add-reaction.yml` 文件，并且只会添加一行修改。
   5. 由于可能出现冲突的情况，助教建议采用强制提交修改历史的操作保持 PR 的原子性。
2. （进阶版-选做）在自己的某个仓库加入类似的功能，提交简单的报告，以博客链接的形式放到本 issue 下方。

   1. 不必和课程提供的练习一致，比如 reaction 内容还有 heart 等其他选择。
   2. 反馈格式：

   ```markdown
   51215903062
   仓库链接： https://github.com/TieWay59/issue-action-test
   报告链接： https://github.com/TieWay59/issue-action-test
   ```

3. 截止时间：5 月 28 日 23:59，请在截止日期前提交 PR，并确保 PR 能够被合并。逾期提交或提交失败的作业将不予评分。

[^1]: [Create reaction for an issue comment](https://docs.github.com/en/rest/reactions?apiVersion=2022-11-28#create-reaction-for-an-issue-comment)
[^2]: [What is the application/vnd.github+json media type? - Stack Overflow](https://stackoverflow.com/questions/62098519/what-is-the-application-vnd-githubjson-media-type)
[^3]: [Creating a personal access token - GitHub Docs](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)
